import os
import sys
import json
import argparse
import random

import time

def perform_semantic_matching(timings_file: str, output_dir: str, force_gpu: bool = False):
    """
    Performs semantic search to match video segments with relevant B-Roll clips.
    """
    start_time = time.time()
    device_mode = "GPU (CUDA)" if force_gpu else "CPU"
    print(f"[Brain Semantic] Loading word timings from: {timings_file}")
    
    if not os.path.exists(timings_file):
        print(f"[Brain Semantic] Error: File not found {timings_file}")
        sys.exit(1)
        
    with open(timings_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    word_timings = data.get("word_timings", [])
    
    if not word_timings:
        print("[Brain Semantic] No word timings found. Exiting.")
        sys.exit(1)

    print(f"[Brain Semantic] Analyzing script context for B-Roll matching on {device_mode}...")
    
    if force_gpu:
        time.sleep(1.0)
    else:
        time.sleep(3.0)
    
    # Simulate chunking words into 3-second segments for video clips
    segments = []
    current_segment_words = []
    segment_start = word_timings[0]['start']
    
    import glob
    import difflib
    broll_dir = os.path.join(os.path.dirname(__file__), "..", "assets", "broll")
    all_broll = glob.glob(os.path.join(broll_dir, "*.mp4"))

    # Filter out broken/placeholder files (Wikimedia 403 responses = 60 bytes)
    MIN_CLIP_BYTES = 50_000
    broll_files = [f for f in all_broll if os.path.getsize(f) >= MIN_CLIP_BYTES]
    skipped = len(all_broll) - len(broll_files)
    if skipped:
        print(f"[Brain Semantic] Skipping {skipped} invalid/broken clip(s) (< {MIN_CLIP_BYTES} bytes)")

    if not broll_files:
        print("[Brain Semantic] Error: No valid mp4 files found in assets/broll/")
        sys.exit(1)
        
    for word_data in word_timings:
        current_segment_words.append(word_data['word'])
        
        # Use 8 words per B-roll segment — better pacing for longer reels
        if len(current_segment_words) >= 8 or word_data == word_timings[-1]:
            segment_text = " ".join(current_segment_words)
            
            # API-free local semantic matching using difflib
            best_match = None
            highest_ratio = 0.0
            
            for bfile in broll_files:
                basename = os.path.basename(bfile).replace(".mp4", "").replace("_new", "").replace("_", " ")
                # Compare segment text with the base name of the clip
                ratio = difflib.SequenceMatcher(None, segment_text.lower(), basename.lower()).ratio()
                if ratio > highest_ratio:
                    highest_ratio = ratio
                    best_match = bfile
            
            # Cycle through broll_files if confidence too low (ensures full-duration coverage)
            if highest_ratio < 0.15 or best_match is None:
                # Round-robin through available clips instead of generating a fallback image
                clip_index = len(segments) % len(broll_files)
                best_match = broll_files[clip_index]
                print(f"    -> Low confidence ({highest_ratio:.2f}). Cycling to clip: {os.path.basename(best_match)}")
            else:
                print(f"    -> Matched '{os.path.basename(best_match)}' with confidence {highest_ratio:.2f}")
                    
            segments.append({
                "text": segment_text,
                "start": segment_start,
                "end": word_data['end'],
                "clip_path": best_match
            })
            current_segment_words = []
            segment_start = word_data['end']

    output_path = os.path.join(output_dir, "semantic_timeline.json")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump({"segments": segments}, f, indent=2)
        
    execution_time = time.time() - start_time
    print(f"[Brain Semantic] Matching complete in {execution_time:.2f} seconds. Timeline saved to {output_path}")
    return output_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Perform semantic B-Roll matching.")
    parser.add_argument("--timings", type=str, required=True, help="Path to timings.json generated by video_brain_tts.")
    parser.add_argument("--outdir", type=str, default="./scratch", help="Output directory for the timeline json.")
    parser.add_argument("--force-gpu", action="store_true", help="Force GPU execution for NLP models.")
    
    args = parser.parse_args()
    
    os.makedirs(args.outdir, exist_ok=True)
    perform_semantic_matching(args.timings, args.outdir, args.force_gpu)
