"use client";

import { useState } from "react";
import { ConfirmForm, ForgetButton } from "./MemoryActions";
import { purgeMemory } from "../actions/memory";

function formatContent(content: string, sector: string) {
  try {
    // 1. Try to parse as JSON first
    const data = JSON.parse(content);
    return JSON.stringify(data, null, 2);
  } catch (e) {
    // 2. Not JSON. Check if it's the specific AST string format generated by sync_neural_memory.py
    if (sector === "structural" && content.startsWith("AST Node:")) {
      // Example: "AST Node: code in .vscode/settings.json\nSymbol: **/*.log"
      const lines = content.split('\n');
      if (lines.length >= 2) {
        const fileMatch = lines[0].match(/in (.+)$/);
        const symbolMatch = lines[1].match(/Symbol: (.+)$/);
        
        if (fileMatch && symbolMatch) {
          return `A structural component named '${symbolMatch[1]}' is located inside \`${fileMatch[1]}\`.`;
        }
      }
    }
    
    // 3. Fallback to raw string
    return content;
  }
}

export default function MemoryTile({ mem, layout = 'grid' }: { mem: any, layout?: 'grid' | 'list' }) {
  const [minimized, setMinimized] = useState(true);

  const isEpisodic = mem.sector === 'episodic';
  const isSemantic = mem.sector === 'semantic';
  // Default to procedural if not episodic or semantic
  
  const accentColor = isEpisodic ? 'border-l-blue-500' : isSemantic ? 'border-l-purple-500' : 'border-l-emerald-500';
  const glowColor = isEpisodic ? 'text-blue-500/40' : isSemantic ? 'text-purple-500/40' : 'text-emerald-500/40';
  const badgeColor = isEpisodic ? 'text-blue-400' : isSemantic ? 'text-purple-400' : 'text-emerald-400';

  const formattedContent = formatContent(mem.content, mem.sector);
  const isJson = formattedContent.startsWith('{') || formattedContent.startsWith('[');
  
  // Truncate logic
  const displayContent = minimized && formattedContent.length > (layout === 'list' ? 100 : 150) 
    ? formattedContent.substring(0, layout === 'list' ? 100 : 150) + "..." 
    : formattedContent;

  const salience = typeof mem.salience === 'number' ? mem.salience.toFixed(2) : "1.00";

  if (layout === 'list') {
    return (
      <div className={`p-4 flex items-center gap-4 group relative border-l-4 ${accentColor} hover:bg-white/5 transition-all duration-300`}>
        <div className="flex-shrink-0 w-24">
          <span className={`text-[9px] font-bold px-2 py-0.5 rounded bg-[var(--surface)] ${badgeColor} tracking-widest uppercase`}>
            {mem.sector || 'unknown'}
          </span>
        </div>
        <div className="flex-shrink-0 w-16">
          <span className={`text-[9px] font-mono ${glowColor}`}>ID: {mem.id?.substring(0, 6)}</span>
        </div>
        <div className={`flex-1 text-sm text-[var(--foreground)] truncate ${isJson ? 'font-mono text-xs' : 'font-light italic'}`} title={formattedContent}>
          {isJson ? displayContent : `"${displayContent}"`}
        </div>
        <div className="flex-shrink-0 flex items-center gap-3">
          <span className="text-[9px] font-bold px-2 py-0.5 rounded bg-[var(--surface)] text-[var(--muted)] tracking-widest uppercase">
            SAL: {salience}
          </span>
          <ConfirmForm action={purgeMemory.bind(null, 'id', mem.id)} confirmMessage={`Are you sure you want to permanently forget this trace?\nID: ${mem.id?.substring(0, 8)}`}>
            <ForgetButton />
          </ConfirmForm>
        </div>
      </div>
    );
  }

  return (
    <div className={`glass-card p-6 flex flex-col group relative overflow-hidden border-l-4 ${accentColor} hover:shadow-[0_0_30px_-10px] hover:shadow-current transition-all duration-300`}>
      <div className="absolute top-0 right-0 p-3 flex items-center gap-2">
        <button 
          onClick={() => setMinimized(!minimized)}
          className="text-[10px] bg-[var(--surface)] text-[var(--muted)] hover:text-[var(--foreground)] px-2 py-1 rounded transition-colors"
        >
          {minimized ? "MAXIMIZE" : "MINIMIZE"}
        </button>
        <span className={`text-[9px] font-mono ${glowColor}`}>ID: {mem.id?.substring(0, 8)}</span>
      </div>
      
      <div className="flex gap-2 mb-4 mt-2">
        <span className={`text-[9px] font-bold px-2 py-0.5 rounded bg-[var(--surface)] ${badgeColor} tracking-widest uppercase`}>
          {mem.sector || 'unknown'}
        </span>
        <span className="text-[9px] font-bold px-2 py-0.5 rounded bg-[var(--surface)] text-[var(--muted)] tracking-widest uppercase">
          SALIENCE: {salience}
        </span>
      </div>
      
      <div className={`text-sm text-[var(--foreground)] leading-relaxed flex-1 ${isJson ? 'font-mono text-xs whitespace-pre-wrap' : 'font-light italic'}`}>
        {isJson ? displayContent : `"${displayContent}"`}
      </div>
      
      <div className="mt-6 pt-4 border-t border-[var(--border)] flex justify-between items-center">
         <span className="text-[10px] text-[var(--faint)] uppercase font-mono">{new Date().toLocaleDateString()}</span>
         <ConfirmForm action={purgeMemory.bind(null, 'id', mem.id)} confirmMessage={`Are you sure you want to permanently forget this trace?\nID: ${mem.id?.substring(0, 8)}`}>
           <ForgetButton />
         </ConfirmForm>
      </div>
    </div>
  );
}
